# Generated by Django 5.1.6 on 2025-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='color_coin',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Coin Color'),
        ),
    ]
