# Generated by Django 5.1.6 on 2025-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_color_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='color_coin',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Coin Color'),
        ),
    ]
